# Generated by Django 4.0.3 on 2022-03-17 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedCrimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_location', models.CharField(max_length=100)),
                ('type_of_crime', models.CharField(max_length=100)),
                ('date_of_crime', models.CharField(max_length=100)),
                ('crime_description', models.CharField(max_length=100)),
                ('crime_date', models.DateTimeField(auto_now_add=True)),
                ('crimeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccounts.users')),
            ],
            options={
                'verbose_name': 'Reported Crimes',
                'verbose_name_plural': 'Reported Crimes',
            },
        ),
    ]
