# Generated by Django 4.0.3 on 2022-03-20 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbvcrimereportapp', '0002_remove_reportedcrimes_crimeid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportedCrimes',
            new_name='Report',
        ),
        migrations.AlterModelOptions(
            name='report',
            options={},
        ),
    ]
