# Generated by Django 4.0.3 on 2022-03-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_acc_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
