# Generated by Django 4.0.3 on 2022-03-18 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0002_alter_users_user_acc_creation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='username',
        ),
    ]
