# Generated by Django 4.0.3 on 2022-03-23 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0003_rename_name_users_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='person_name',
        ),
    ]
