# Generated by Django 4.0.3 on 2022-03-23 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0004_rename_username_users_person_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
